### ISSUE TITLE
Tutorials don't work

### ISSUE THREAD

**Issue by g7pvs** [gvec-group/gvec#8]
When running the gvec tutorial on jupyter notebook the code works OK up to the following instruction on the first tutorial, but then produces an error:

fig, axs = state.plot_radial_profile(
    quantities=["iota", "p"],
    xaxis="rho_squared",
)

The error is shows below:

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[18], line 1
----> 1 fig, axs = state.plot_radial_profile(
      2     quantities=["iota", "p"],
      3     xaxis="rho_squared",
      4 )

AttributeError: 'State' object has no attribute 'plot_radial_profile'

The other tutorials have similar errors, I presume this is because the code has been updated and tutorial is yet to be updated.

**Comment by fhindenlang** [comment]
Please identify yourself.

Yes, you are right, we have different documentation versions for the different versions of GVEC.
On readthedocs, the "latest" documentation is shown by default, and is built from the latest `develop` branch. 

That is not the same as the latest release, which is on par with the `main` branch. For the latest release v1.3,  there is a "v1.3" documentation, which you can select on the top left in the readthedocs. The tutorials there should then be compatible with that version of gvec.
Can you check the version of gvec you installed ? 
```pygvec --version```

To install the gvec version that runs with the "latest" documentation, you need to directly install gvec from the develop branch:
```
pip install git+https://gitlab.mpcdf.mpg.de/gvec-group/gvec.git@develop
```
We are working on the next release (v1.4), it should be out in ~2 weeks.

**Comment by g7pvs** [comment]
Sorry (user error) - I had downloaded the latest (1.3) and had "latest" selected for the user documentation - selecting the "latest" at the top left appears to select documentation for version 1.2 which explains why it didn't work.
Selecting "1.3" at the top left gives the correct tutorials that now work.
Thanks for you help and quick response.

**Comment by Rykath** [comment]
Yes, there is an issue with which documentation is shown per default, which can be confusing. Thanks for pointing this out. We will fix this in the coming days.

**Comment by Rykath** [comment]
The default documentation is now the latest PyPI release.
